fix: get input data based on address type
unchained-capital/unchained-bitcoin pull request #74
Opened 2023-03-02 01:43 UTC by bucko13

Some eslint fixes got caught in this but basically the input data for adding to a psbt needs to be a bit smarter about how it gets the input data for ledger v2 which is pickier about when it requires nonWitnessUtxo vs witnessUtxo data. (See [here](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki#simple-signer-algorithm) from the bip174 docs).

Unfortunately while this creates a valid PSBT that ledger will sign, the signatures created after getting converted to psbtv2 and getting passed to the ledger are still wrong so there's still some tweaking left to do.

2023-03-02 01:44 UTC, bucko13 commented on src/psbt.js
> +
this is basically the only relevant change

2023-03-02 18:30 UTC, Shadouts approved these changes

2023-03-02 18:40 UTC, Shadouts requested changes
I know we talked about this out-of-band, but there are still some signature test failures on this which is to be expected since the psbt contents are changing.

2023-03-02 19:20 UTC, Shadouts commented
I went to go see about the sigs myself, but I'm still getting invalid data error `0x6a80`

2023-03-02 20:15 UTC, bucko13 commented
@Shadouts thats weird…

2023-03-06 17:44 UTC, bucko13 commented
So, the correct behavior for this is that if it's `P2SH-P2WSH` then BOTH nonWitnessUtxo and witnessUtxo should be included in the PSBT. Unfortunately bitcoinjs-lib doesn't allow you to do this though. I've filed a [bug](https://github.com/bitcoinjs/bitcoinjs-lib/issues/1894). Hopefully it'll be addressed and we can fix the input serialization in the correct way such that signatures are created correctly. Without this change, ledger will fail b/c it has incorrect data. With this change, ledger will succeed but will produce incorrect signatures so it's not quite ready for primetime.

2023-09-08 17:14 UTC, bucko13 commented
Not required anymore for now. Closing.

2023-09-08 17:14 UTC, closed without merging